### PR TITLE
styles: Fix header and footer

### PR DESCRIPTION
**Pull request by jrcastro2**
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/248
### Before
screencapture-127-0-0-1-5000-communities-1231111-settings-2020-08-25-10_11_50

### After
screencapture-127-0-0-1-5000-communities-123111-settings-2020-08-25-10_03_50

### CODE REVIEW

**Comment by Glignos** [comment]
@jrcastro2 Could you just post a screenshot of how it looks after removing it? :)

**Comment by jrcastro2** [comment]
> @jrcastro2 Could you just post a screenshot of how it looks after removing it? :)

The screenshot that is already in the PR is how it looks like after removing it, I will add another screenshot to show how it looked like before adding it :)

**Review by Glignos — COMMENTED** [review]
I think this change is currently breaking other UI pages in communities. E.g. community details
Screenshot 2020-08-24 at 15 53 25
Maybe a solution would be to specify a different class for the cases that this is causing issues. :)

**Review by Glignos — APPROVED** [review]
LGTM 👍

**Pull request merged**
