### PR TITLE
models: rename foreign keys

### LINKED ISSUE #63: models: rename foreign keys from `id_*` to `*_id`
- following discussion in https://github.com/inveniosoftware/invenio-groups/issues/39#issuecomment-238219783
- addresses #61 
## 

cc @lnielsen

### PR DESCRIPTION
**Pull request by alizeepace**
closes #63

### CODE REVIEW

**Comment by lnielsen** [comment]
I will merge this PR, as if merged now it will break Zenodo, so it has to wait until after Zenodo launch.

**Comment by jirikuncar** [comment]
@lnielsen can you pin the Invenio-Community version on Zenodo?

**Comment by lnielsen** [comment]
@jirikuncar No, since if we need to fix a problem, then we're forced to fix all the foreign keys as well. Zenodo is the only service using Communities module now, so the PR can stick around until we're ready.

Only alternative is to create a ``next`` branch and merge it there.

@alizeepace Just to be clear, there is no problem with the changes. My comments are just about timing when to apply them.

**Comment by jirikuncar** [comment]
@lnielsen since Zenodo is out, can we merge this PR?

**Comment by lnielsen** [comment]
@jirikuncar We're still fixing lots of bugs, and I prefer if we can wait with the update until we're out of bug fixing mode. Alternatively we can create a 1.0.0 final release with the current state, so that there's a maintenance branch that can receive fixes and that we can make releases from.

**Comment by tiborsimko** [comment]
I wouldn't create any `maint-1.0` for an alpha package. It would be akin to sending mixed signals. The usual meaning we are trying to advertise is:

- alpha status: fast pace, don't look, no promises, API may change frequently, etc
- beta status: documentation exists, you can start looking at the package, but no data migration is provided 
- production status: data migration is fully supported, M.N.0 is released , `maint-M.N` is created

We could take this example to start musing about data migration related to table changes, but I'd say it's probably not worth it yet.  So I'd vote for option 2, merging whenever Zenodo is ready.

**Comment by tiborsimko** [comment]
(That said, we'll face this situation sooner or later with other packages, so we should start thinking of taking *something* for an easy first data migration use case... We won't be able to postpone for much longer. But I'd say let's targe another, more stable package example, which may be perhaps more appropriate.  The communities is still young. See also related musings in https://github.com/inveniosoftware/invenio-github/pull/30#issuecomment-248859188)

**Comment by jirikuncar** [comment]
@lnielsen it would be nice to do a release with the initial alembic recipes before integrating this PR. I have added a test case especially for the latest upgrade script so it should be good for a final review.

**Comment by lnielsen** [comment]
Closing as Invenio-Communities is being completely revamped.

**Pull request closed without merging**
