### PR TITLE
Editor: Update RichEditor to use inputValue

### PR DESCRIPTION
**Pull request by Samk13**
:heart: Thank you for your contribution!

### Description

This will fix the editor's loss of content after losing focus in communities invite modal
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2771
Related to https://github.com/inveniosoftware/react-invenio-forms/pull/249

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [ ] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [ ] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [ ] I've added relevant test cases.
- [ ] I've added relevant documentation.
- [ ] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/howtos/i18n/).
- [ ] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [ ] I've NOT included third-party code (copy/pasted source code or new dependencies).
    * If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Frontend**

- [ ] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines.
- [ ] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines.
- [ ] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines.

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Review by max-moser — APPROVED** [review]
basically the same change as in https://github.com/inveniosoftware/react-invenio-forms/pull/249

**Review by max-moser — APPROVED** [review]
with some quick testing (of the community member invitation modal) on a local v13 i couldn't find the issue of the editor losing content when losing focus.
however, i could find this issue in a v12 setup and this PR fixed that.
on v13, i could not detect any adverse effects with this PR.

**Comment by Samk13** [comment]
> with some quick testing (of the community member invitation modal) on a local v13 i couldn't find the issue of the editor losing content when losing focus. however, i could find this issue in a v12 setup and this PR [(backported)](https://github.com/inveniosoftware/invenio-communities/pull/1187) fixed that. on v13, i could not detect any adverse effects with this PR.

From my testing, this issue appears to be flaky, it sometimes works and sometimes doesn't, which was confusing. Therefore, I've decided to keep this change for now, as it guarantees the functionality. 
Unless a cleaner solution is found, we'll proceed with this.
For the failing CI I added this one: https://github.com/inveniosoftware/invenio-communities/pull/1186 so no need to worry about it.

**Comment by max-moser** [comment]
alright, thanks for the extra infos!
as an immediate fix, i just replaced `docker-compose --version` with `docker compose version`.
when the CI actions get reworked, this will be replaced anyway :)

**Pull request merged**
