### PR TITLE
members dropdowns: change descriptions

### PR DESCRIPTION
**Pull request by NRodriguezcuellar**
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1601
Screenshot from 2022-05-18 16-59-52
Screenshot from 2022-05-18 16-59-40

### CODE REVIEW

**Comment by kpsherva** [comment]
I am not sure if fully addresses the issue. Dropdown still different than the mockup. Missing icon and the dropdown option area (after opening the dropdown) is wider on the mockups than in the current view

**Comment by NRodriguezcuellar** [comment]
> I am not sure if fully addresses the issue. Dropdown still different than the mockup. Missing icon and the dropdown option area (after opening the dropdown) is wider on the mockups than in the current view

how i understood it, it was mainly about the text, maybe @lnielsen  can clarify.

**Comment by lnielsen** [comment]
Ok as is as we need it for the release. We can add the icons in a later stage because of time pressure.

**Comment by zzacharo** [comment]
will merge but created an issue about the design https://github.com/inveniosoftware/invenio-app-rdm/issues/1636

**Pull request merged**
