### PR TITLE
members: patch pagination rendering to prevent infinite negative numbers

### PR DESCRIPTION
**Pull request by Samk13**
:heart: Thank you for your contribution!

### Description

* Conditionally render the Pagination component based on total results
* Only show Pagination if total results exceed results per page
* Ensures cleaner UI and prevents unnecessary pagination rendering
* Closes https://github.com/inveniosoftware/invenio-communities/issues/1136

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [x] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [x] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [x] I've added relevant test cases.
- [x] I've added relevant documentation.
- [x] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/howtos/i18n/).
- [x] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [x] I've NOT included third-party code (copy/pasted source code or new dependencies).
    * If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Frontend**

- [x] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines.
- [x] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines.
- [x] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines.

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Comment by Samk13** [comment]
Should add the `showWhenOnlyOnePage` prop when [268](https://github.com/inveniosoftware/react-searchkit/pull/268) is merged.

**Comment by anikachurilova** [comment]
Thank you for taking care of this! Good job 🚀 
After having a look and doing a quick test, the pagination still seems to be not appearing when there are more results found than shown on the page (see the screenshot)
Screenshot 2024-06-26 at 13 25 03
Please correct me if I am checking something wrong!

**Comment by Samk13** [comment]
@anikachurilova 
I've updated the value, which works as expected for numbers under the default pagination value see screenshots. 
However, the issue persists with larger numbers, specifically when there are more than 25 members. 

This patch mitigates the issue for a smaller group of users only. Feel free to close if this is not an acceptable temporary solution.
test-pagination-3

**Comment by Samk13** [comment]
Final result:

test-pagination-4

**Comment by kpsherva** [comment]
closing in favour of https://github.com/inveniosoftware/invenio-communities/pull/1207 (adresses the underlying issue with state management)

**Pull request closed without merging**
